config/routes.rb
Rails.application.routes.draw do
  resources :gungemes
  root "gungemes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gungeme.rb
class Gungeme < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gungemes_controller.rb
class GungemesController < ApplicationController
  before_action :set_gungeme, only: [:show, :edit, :update, :destroy]

  # GET /gungemes
  # GET /gungemes.json
  def index
    @gungemes = Gungeme.all
  end

  # GET /gungemes/1
  # GET /gungemes/1.json
  def show
  end

  # GET /gungemes/new
  def new
    @gungeme = Gungeme.new
  end

  # GET /gungemes/1/edit
  def edit
  end

  # POST /gungemes
  # POST /gungemes.json
  def create
    @gungeme = Gungeme.new(gungeme_params)

    respond_to do |format|
      if @gungeme.save
        format.html { redirect_to @gungeme, notice: 'Gungeme was successfully created.' }
        format.json { render :show, status: :created, location: @gungeme }
      else
        format.html { render :new }
        format.json { render json: @gungeme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gungemes/1
  # PATCH/PUT /gungemes/1.json
  def update
    respond_to do |format|
      if @gungeme.update(gungeme_params)
        format.html { redirect_to @gungeme, notice: 'Gungeme was successfully updated.' }
        format.json { render :show, status: :ok, location: @gungeme }
      else
        format.html { render :edit }
        format.json { render json: @gungeme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gungemes/1
  # DELETE /gungemes/1.json
  def destroy
    @gungeme.destroy
    respond_to do |format|
      format.html { redirect_to gungemes_url, notice: 'Gungeme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gungeme
      @gungeme = Gungeme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gungeme_params
      params.require(:gungeme).permit(:name, :machine, :purpose, :vc, :friendid, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gungemes_helper.rb
module GungemesHelper
end

app/views/gungemes/_form.html.erb
<%= form_with(model: gungeme, local: true) do |form| %>
  <% if gungeme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gungeme.errors.count, "error") %> prohibited this gungeme from being saved:</h2>

      <ul>
      <% gungeme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :machine %>
    <%= form.number_field :machine %>
  </div>

  <div class="field">
    <%= form.label :purpose %>
    <%= form.number_field :purpose %>
  </div>

  <div class="field">
    <%= form.label :vc %>
    <%= form.number_field :vc %>
  </div>

  <div class="field">
    <%= form.label :friendid %>
    <%= form.text_field :friendid %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gungemes/edit.html.erb
<h1>Editing Gungeme</h1>

<%= render 'form', gungeme: @gungeme %>

<%= link_to 'Show', @gungeme %> |
<%= link_to 'Back', gungemes_path %>

app/views/gungemes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gungemes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Machine</th>
      <th>Purpose</th>
      <th>Vc</th>
      <th>Friendid</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gungemes.each do |gungeme| %>
      <tr>
        <td><%= gungeme.name %></td>
        <td><%= gungeme.machine %></td>
        <td><%= gungeme.purpose %></td>
        <td><%= gungeme.vc %></td>
        <td><%= gungeme.friendid %></td>
        <td><%= gungeme.comment %></td>
        <td><%= link_to 'Show', gungeme %></td>
        <td><%= link_to 'Edit', edit_gungeme_path(gungeme) %></td>
        <td><%= link_to 'Destroy', gungeme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gungeme', new_gungeme_path %>

app/views/gungemes/new.html.erb
<h1>New Gungeme</h1>

<%= render 'form', gungeme: @gungeme %>

<%= link_to 'Back', gungemes_path %>

app/views/gungemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gungeme.name %>
</p>

<p>
  <strong>Machine:</strong>
  <%= @gungeme.machine %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @gungeme.purpose %>
</p>

<p>
  <strong>Vc:</strong>
  <%= @gungeme.vc %>
</p>

<p>
  <strong>Friendid:</strong>
  <%= @gungeme.friendid %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @gungeme.comment %>
</p>

<%= link_to 'Edit', edit_gungeme_path(@gungeme) %> |
<%= link_to 'Back', gungemes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeizibanApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>